server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daniel-pinna/pinna-config-server
          search-paths: 'greeting-service*'
#          username: user
#          password: pass
#          default-label: main
#  profiles:
#    active:
#      - native
